name: autobuild

on:
  schedule:
    - cron: '20 5 * * *'
  push:
  workflow_dispatch:
    branches:
      - 'main'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        arch: [x86, x64]
        index: [0, 1, 2, 3, 4]
        options: [dll, static]

    runs-on: windows-latest

    timeout-minutes: 60

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup nasm
        uses: ilammy/setup-nasm@v1

      - name: Setup Visual Studio
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{matrix.arch}}

      - name: Build
        run: .scripts/autobuild.ps1 ${{matrix.index}} ${{matrix.options}}

      - name: Upload
        if: ${{github.ref == 'refs/heads/main'}}
        env:
          SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
        run: |
          if (Test-Path -Path *.zip) {
            $env:SSH_PRIVATE_KEY | Set-Content identity
            icacls identity /grant:r runneradmin:R /c
            icacls identity /inheritance:r /c
            scp -i identity -o StrictHostKeyChecking=no -o PasswordAuthentication=no *.zip ${{secrets.SSH_TARGET}}
          }
